version: '3.3'
services:
  traefik:
    image: traefik
    deploy:
      resources:
        limits:
          memory: 30M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/etc/traefik/acme/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8181:8181"
